create database polling;
use polling;
create table adminlogin(username varchar(25),password varchar(25));
insert into adminlogin values("karthik","123");
insert into adminlogin values("admin","polling");
select * from adminlogin;
use polling;
create table userlogin(firstname varchar(25),lastname varchar(25),age int,crepass varchar(25),conpass varchar(25));
select * from userlogin;
delete from userlogin where firstname='voter';
delete from userlogin where firstname='kar';
Select * from userlogin;
delete from userlogin where crepass=1111;
use polling;
delete from userlogin where crepass=1111;
select * from userlogin;
delete from userlogin where firstname='voter';
delete from userlogin where crepass=123;
select * from adminlogin;
select * from userlogin;
create table voter(vid varchar(11),votname varchar(25),bdate date,vadd varchar(25),vage int,gender char(1),vphone varchar(11),constituency varchar(35),primary key(vid));
desc voter;
insert into voter values('12345678912','Ramesh','1995-11-12','blore','23','m','234009','basvangudi');
insert into voter values('12345678945','Rajesh','1996-12-06','blore','23','m','234009','rrnagar');
insert into voter values('12345678975','Suresh','1989-03-23','mysore','23','m','234009','Hunsur');
insert into voter values('12345678933','Ramya','1975-10-13','mysore','43','f','229635','Nanjangud');
update voter set vage='22' where vid='12345678912';
update voter set vphone=235678 where vid='12345678945';
update voter set vage=29 where vid=12345678975;
update voter set vphone=256789 where vid=12345678975;
insert into voter values('12345678956','Vijaya','1990-11-12','blore','28','f','233824','basvangudi');
create table election(ename varchar(25),ncand int,edate date,primary key(ename));
select * from election;
desc election;
select* from adminlogin;
delete from adminlogin where username='katu';
create table candidate(canid varchar(5),votid varchar(11),cname varchar(25),party varchar(25),cage int,gender char(1),rating int,primary key(canid));
alter table candidate add foreign key(votid)references voter(vid);
select * from candidate;
use polling;
select * from candidate;
drop table election;
drop table candidate;
create table election(eid varchar(5),ename varchar(25),edate date,primary key(eid));
create table candidate(ceid varchar(5),canid varchar(5),votid varchar(11),cname varchar(25),party varchar(25),cage int,gender char(1),primary key(ceid,canid));
alter table candidate add foreign key(ceid) references election(eid) on delete cascade;
alter table candidate add foreign key(votid) references voter(vid) on delete cascade;
select * from election;
create table voting(elid varchar(5),vild varchar(5),vname varchar(25),primary key(elid,vild));
alter table voting add foreign key(elid) references election(eid);
alter table voting add foreign key(vild) references voter(vid);
SELECT * FROM voter;
select * from candidate;
delete from voting where elid=10110;
call result();
desc voting;
select * from voting;
drop table voting;
create table voting(vid varchar(11),elid varchar(5),canid varchar(5),cname varchar(25),primary key(vid,elid,canid));
select * from userlogin;
delete from userlogin;
desc userlogin;
drop table userlogin;
create table userlogin(fname varchar(25),lname varchar(25),age int,crepass varchar(25),conpass varchar(25));

desc candidate;
drop table candidate;
create trigger updatrat
after update on candidate
for each row
update candidate
set rating=rating+1;
select * from election;
desc election;
select * from candidate;
update candidate set rating=5 where canid=10019;
select * from candidate;
drop table election;
drop table candidate;
create table election(eid varchar(5),ename varchar(25),edate date,primary key(eid,ename));
select * from election;
call result();
desc voting;
alter table voting add foreign key(vid)references voter(vid) on delete cascade;
alter table voting add foreign key(elid)references election(eid)on delete cascade;
alter table voting add foreign key(canid)references candidate(canid);
select * from voting;
call result();
desc voting;
drop table CANDIDATE;
select * from voter;
desc voting;
show tables;
create trigger end_ele
after delete on election
for each row
delete from voting where elid=old.eid;
drop trigger end_ele;
desc voting;
